export const COMPARISON_EXCLUDE: string[] = [
  'Razon A/G',
  'Raz',
  'CHCM',
  'Conc.Hb.Corp',
  'Baciliformes',
  'Mielocitos',
  'Juveniles',
  'Blastos',
  'Promielocitos',
  'sO2c',
  'CO2 TOTAL',
  'Hora',
  'Veloc. Filtr. Glomer',
  'Veloc Filtr',
  'Deseable',
  'Indice de riesgo',
  'Hemoglobina Glicosilada',
  'Glucosa promedio',
  'Normal',
  'Muy alto',
  'Recuento Hematies',
  'Basofilos',
  'Control',
  ', OT',
  'VLDL',
  'RDW',
  'Amilasa',
  'BEecf',
  'Globulinas',
  'N° de ingreso',
  'Nº de ingreso',
  'N° ingreso',
  'Nº ingreso',
  'No de ingreso',
  'Numero de ingreso',
  'MIDAS',
  'Tipo de muestra',
];

export const COMPARISON_ORDER: string[] = [
  'Recuento Leucocitos',
  'Hemoglobina',
  'Hematocrito',
  'VCM',
  'HCM',
  'Recuento de Plaquetas',
  'Segmentados',
  'Linfocitos',
  'Monocitos',
  'Eosinofilos',
  'Proteina C Reactiva',
  'VHS',
  'LDH',
  'Creatinina',
  'RPC',
  'RAC',
  'Nitrogeno Ureico',
  'Uremia',
  'Sodio',
  'Potasio',
  'Cloro',
  'HCO3',
  'Calcio',
  'Fosforo',
  'Cuerpos Cetónicos',
  'Proteínas',
  'Nitritos',
  'Densidad',
  'Leucocitos',
  'Eritrocitos',
  'Bacterias',
  'Cilindros',
  'Placas de pus',
  'pH',
  'pCO2',
  'pO2',
  'Lactato',
  'ASAT/GOT',
  'ALAT/GPT',
  'GGT',
  'Fosfatasa Alcalina',
  'Bilirrubinas',
  'Lipasa',
  'Protrombina',
  'TTPK',
  'INR',
  'Albumina',
  'Proteinas Totales',
  'Troponina',
  'Dimero',
  'CK Total',
  'Magnesio',
  'TSH',
  'T4L',
  'T4 Libre',
  'Acido Urico',
  'Glicemia',
  'Hemoglobina Glicosilada',
  'Colesterol Total',
  'LDL',
  'HDL',
  'TG',
  'Trigliceridos',
  'Cuerpos Ceton',
  'Cetonemia',
];

export const COMPARISON_DISPLAY_GROUPS = [
  {
    label: 'Hemograma',
    patterns: [
      'Recuento Leucocitos',
      'Hemoglobina',
      'Hematocrito',
      'VCM',
      'HCM',
      'Recuento de Plaquetas',
      'Segmentados',
      'Linfocitos',
      'Monocitos',
      'Eosinofilos',
    ],
  },
  {
    label: 'Inflamación',
    patterns: ['Proteina C Reactiva', 'VHS', 'LDH'],
  },
  {
    label: 'Función renal / electrolitos',
    patterns: [
      'Creatinina',
      'Nitrogeno Ureico',
      'Uremia',
      'Sodio',
      'Potasio',
      'Cloro',
      'HCO3',
      'Calcio',
      'Fosforo',
    ],
  },
  {
    label: 'Coagulación',
    patterns: ['Protrombina', 'TTPK', 'INR', 'Dimero'],
  },
  {
    label: 'Perfil hepático',
    patterns: [
      'ASAT/GOT',
      'ALAT/GPT',
      'GGT',
      'Fosfatasa Alcalina',
      'Bilirrubinas',
      'Albumina',
      'Proteinas Totales',
    ],
  },
  {
    label: 'RPC / RAC',
    patterns: ['RPC', 'RAC'],
  },
  {
    label: 'Metabólico',
    patterns: [
      'Hemoglobina Glicosilada',
      'Acido Urico',
      'Glicemia',
      'TSH',
      'T4L',
      'T4 Libre',
      'Colesterol Total',
      'LDL',
      'HDL',
      'TG',
      'Trigliceridos',
    ],
  },
] as const;

export const COMPARISON_PINNABLE_VARIABLES = [
  'Creatinina',
  'Proteina C Reactiva',
  'RPC',
  'RAC',
  'Hemoglobina',
];

export const COMPARISON_GROUP_ORDER = [
  'Hemograma',
  'Inflamación',
  'Función renal / electrolitos',
  'Coagulación',
  'Perfil hepático',
  'RPC / RAC',
  'Metabólico',
  'Otros',
] as const;

export type ComparisonGroupLabel = (typeof COMPARISON_GROUP_ORDER)[number];
